#+TITLE: Surface night lights in Mexico at analytical units
#+AUTHOR: Eric Magar

----------

Last revision: 2021-04-29


*New script* ~code/extract-state-yr-mu-returns.r~  exports municipal election returns. Focus in a single state-year allows votes received by each party across municipalities grouped in one column each --- easier to describe.  

----------

# Export to md: M-x org-md-export-to-markdown

* Description of /Surface night lights in Mexico at analytical units/ repository
- Author: Eric Magar
- Location https://github.com/emagar/luminosity
- Email: emagar at itam dot mx

The repository contains nighttime luminosity data for Mexico, aggregated at the municipal ($N \approx 2,500$) and /sección electoral/ levels ($N \approx 67,000$). Luminosity rasters are from [[https://www.nature.com/articles/s41597-020-0510-y][Li, Zhou, Zhao and Zhao]]'s (2020) Harmonized Global Nighttime Light Dataset 1992-2018. 

The source reports annual geo-coded observations at a spatial resolution of about one square kilometer (30 arc seconds). This repository summarizes pixels across each unit's territory, reporting unit mean luminosity, the median, and the standard deviation. The source averages (and harmonizes) pixel luminosity in time. This repo averages pixels in space. 

Here one example. 


